name: 'Terraform destroy'

on:
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'friendly-brand-441407-b4'
          workload_identity_provider: 'projects/475047423340/locations/global/workloadIdentityPools/terrafom-pool-id/providers/github-oidc-provider'
          service_account: 'terraform-sa@friendly-brand-441407-b4.iam.gserviceaccount.com'

      # Terraform Cleanup
      - name: Terraform Cleanup
        run: rm -rf .terraform

        # Setup Terraform
      - name: init Terraform
        run: terraform init

      # Destroy Terraform
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
