name: 'Terraform destroy'

on:
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read

jobs:
  

  destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: approval-required # Add environment with required approval

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'friendly-brand-441407-b4'
          workload_identity_provider: 'projects/475047423340/locations/global/workloadIdentityPools/terrafom-pool-id/providers/github-oidc-provider'
          service_account: 'terraform-sa@friendly-brand-441407-b4.iam.gserviceaccount.com'

      - name: Debug
        run: |
          echo "===========================GOOGLE_GHA_CREDS_PATH====================================="
          cat $(echo $GOOGLE_GHA_CREDS_PATH) | jq
          echo "===========================GOOGLE_APPLICATION_CREDENTIALS====================================="
          cat $(echo $GOOGLE_APPLICATION_CREDENTIALS) | jq
          echo "===========================CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE====================================="
          cat $(echo $CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE) | jq

        # Setup Terraform
      - name: init Terraform
        run: terraform init

      # Destroy Terraform
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
