name: 'Terraform CI'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1        

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'friendly-brand-441407-b4'
          workload_identity_provider: 'projects/475047423340/locations/global/workloadIdentityPools/terrafom-pool-id'

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        # env:
        #   GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      # Plan Terraform
      - name: Terraform Plan
        run: terraform plan
        # env:
        #   GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      # Apply Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve
        # env:
        #   GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}