name: 'Terraform CI'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Add manual trigger for destroy step
    inputs:
      confirm_destroy:
        description: 'Type YES to confirm destroying infrastructure'
        required: true

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1        

      # Initialize a new or existing Terraform working directory
      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      # Build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        if: github.event_name != 'workflow_dispatch'
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

  destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    needs: terraform # Wait for the Terraform job to finish
    if: github.event.inputs.confirm_destroy == 'YES' # Conditional execution based on input

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
