name: 'Terraform CI'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1        

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'friendly-brand-441407-b4'
          workload_identity_provider: 'projects/475047423340/locations/global/workloadIdentityPools/terrafom-pool-id/providers/github-oidc-provider'
          service_account: 'terraform-sa@friendly-brand-441407-b4.iam.gserviceaccount.com'

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Destroy Terraform
      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      # # Plan Terraform
      # - name: Terraform Plan
      #   run: terraform plan

      # # Apply Terraform
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve